on:
  push:
    branches-ignore:
      - prod

jobs:
  build-dev:
    uses: ./.github/workflows/build.yml
    if: github.ref != 'refs/heads/master' # deploy if master

  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    if: github.ref == 'refs/heads/master' # deploy if master
    with:
      stage: dev
